// <auto-generated />
namespace Retro_Indie_Spiel_Webserver.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnpassungenHighscore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnpassungenHighscore));
        
        string IMigrationMetadata.Id
        {
            get { return "201512201523358_AnpassungenHighscore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
